### ISSUE TITLE
Install other theme

### ISSUE THREAD

**Issue by karneaud** [MozaikAgency/wp-theme-bootstrap#101]
AWESOME toolkit! Dare I say way better than SAGE! 

Question.....if one wanted to install another boilerplate theme instead of what you have there....how would  you recommend going about it? child-theme? overriding theme and assets folder( BTW AWESOME idea to separate the assets from php)

**Comment by Maximilianos** [comment]
Hey, thanks for the good words, they are really appreciated!

## Using wp-theme-starter as a child theme

In my mind the easiest should be using the wp-theme-starter as a child theme of the other boilerplate you want to use. In order to use wp-theme-starter as a child theme all you need to do is specify the parent theme's directory as the `parentTheme` property in the `project.config.js` file.

Once you've done that you can develop your child theme almost exactly as you normally would. Just note the following: When you want to override a template/file, the "root" of your theme, in terms of the php files, is in the `theme` folder within the wp-theme-starter. So if you wanted to override some files located in the parent theme like:

```
|- parent-theme
    |- assets
    |- inc
        |- other-file-to-change.php
    |- lib
    |- single-to-change.php
    ...
```

you simply have to copy that structure _within the `theme` directory_ of the child theme:

```
|- child-theme_dev
    |- assets
    |- gulp
    |- theme
        |- inc
            |- other-file-to-change.php
        |- single-to-change.php
    ...
```

## Using the boilerplate entirely within wp-theme-starter

The other option you have, where you want use the boilerplate as a starting point and you don't mind making changes to it, is: Empty out the `theme` folder in wp-theme-starter and drop in all the php files of your boilerplate, then take the boilerplate's assets files and put them in wp-theme-starter's assets folder making sure to maintain the top level structure of the assets folder (put images in img, put scss in scss, put js in js etc).

Once you've done that you shouldn't have much trouble working on those files like you normally would aside from possibly having to refactor some of your javascript to work better with webpack.

**Comment by karneaud** [comment]
thanks...did that!
