### ISSUE TITLE
header.php does not use body_class()

### ISSUE THREAD

**Issue by janw-me** [MozaikAgency/wp-theme-bootstrap#267]
I saw in the header the opening body tag `<body class="site__body">`
It does not use [body_class()](https://developer.wordpress.org/reference/functions/body_class/)
Is there a reason why it is not using it?

IMO it should be:
`<body <?php body_class('site__body') ?>>`

**Comment by Maximilianos** [comment]
Thanks for the question! :)

Yes, this was done on purpose. The wp `body_class` method produces a lot of classes and 99% of the time we found in our projects we did not need or use them or, even worse, they conflicted with names that we wanted to use as BEM blocks on the page (eg `page`). That's why I specifically chose to omit this commonly used method from the starter's `header.php`.

The `class-walker-nav-menu.php` was also implemented to solve a very similar issue we were having with the WP menu. With it, you can have a WP menu with the class modifiers you want and all class names following the BEM naming convention instead of a "mess" of classnames that are only sometimes useful.

Of course, if you do find the output of `body_class` useful then there is nothing wrong with that! :) Feel free to add it when developing, but I do not think we will add it to the starter!

**Comment by iMicknl** [comment]
In addition to @Maximilianos answer, you can also do it this way: 
I am using the body_class() function by default in my forked version of this boilerplate, because it allows me to easily add body_class via the 'WordPress way'. But I am not using all the default WordPress classes anymore.

`add_filter( 'body_class', [ $this, 'filter_body_class' ], PHP_INT_MAX );`

```
    `public function filter_body_class( $classes ) {
        $classes   = [];
        $classes[] = 'site__body';

        if ( is_admin_bar_showing() ) {
            $classes[] = 'site__body--adminbar';
        }

        return $classes;
    }`
```
